/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExecutionStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Null,
  'partial' : IDL.Null,
});
export const ExecutionScope = IDL.Variant({
  'full' : IDL.Null,
  'single' : IDL.Null,
  'partial' : IDL.Null,
});
export const NodeExecutionLog = IDL.Record({
  'nodeId' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'inputs' : IDL.Text,
  'durationMs' : IDL.Nat,
  'outputs' : IDL.Text,
  'nodeType' : IDL.Text,
});
export const AppendExecutionRequest = IDL.Record({
  'status' : ExecutionStatus,
  'scope' : ExecutionScope,
  'durationMs' : IDL.Nat,
  'nodeLogs' : IDL.Vec(NodeExecutionLog),
  'workflowId' : IDL.Text,
});
export const Time = IDL.Int;
export const Execution = IDL.Record({
  'id' : IDL.Text,
  'status' : ExecutionStatus,
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'scope' : ExecutionScope,
  'durationMs' : IDL.Nat,
  'nodeLogs' : IDL.Vec(NodeExecutionLog),
  'workflowId' : IDL.Text,
});
export const WorkflowEdge = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'targetHandle' : IDL.Opt(IDL.Text),
  'target' : IDL.Text,
  'sourceHandle' : IDL.Opt(IDL.Text),
});
export const NodeData = IDL.Record({
  'config' : IDL.Text,
  'nodeType' : IDL.Text,
});
export const NodePosition = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
});
export const WorkflowNode = IDL.Record({
  'id' : IDL.Text,
  'data' : NodeData,
  'position' : NodePosition,
  'nodeType' : IDL.Text,
});
export const CreateWorkflowRequest = IDL.Record({
  'name' : IDL.Text,
  'edges' : IDL.Vec(WorkflowEdge),
  'nodes' : IDL.Vec(WorkflowNode),
});
export const Workflow = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'edges' : IDL.Vec(WorkflowEdge),
  'updatedAt' : Time,
  'nodes' : IDL.Vec(WorkflowNode),
});
export const ExecutionSummary = IDL.Record({
  'id' : IDL.Text,
  'status' : ExecutionStatus,
  'createdAt' : Time,
  'scope' : ExecutionScope,
  'durationMs' : IDL.Nat,
  'workflowId' : IDL.Text,
});
export const ExecutionDetail = IDL.Record({
  'summary' : ExecutionSummary,
  'nodeLogs' : IDL.Vec(NodeExecutionLog),
});
export const ExecutionResult = IDL.Variant({
  'ok' : ExecutionDetail,
  'err' : IDL.Text,
});
export const WorkflowSummary = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'edgeCount' : IDL.Nat,
  'nodeCount' : IDL.Nat,
});
export const UpdateWorkflowRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'edges' : IDL.Vec(WorkflowEdge),
  'nodes' : IDL.Vec(WorkflowNode),
});
export const WorkflowResult = IDL.Variant({
  'ok' : Workflow,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'appendExecution' : IDL.Func([AppendExecutionRequest], [Execution], []),
  'createWorkflow' : IDL.Func([CreateWorkflowRequest], [Workflow], []),
  'deleteWorkflow' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getExecution' : IDL.Func([IDL.Text], [ExecutionResult], ['query']),
  'getWorkflow' : IDL.Func([IDL.Text], [IDL.Opt(Workflow)], ['query']),
  'listExecutions' : IDL.Func([], [IDL.Vec(ExecutionSummary)], ['query']),
  'listWorkflows' : IDL.Func([], [IDL.Vec(WorkflowSummary)], ['query']),
  'updateWorkflow' : IDL.Func([UpdateWorkflowRequest], [WorkflowResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExecutionStatus = IDL.Variant({
    'success' : IDL.Null,
    'failed' : IDL.Null,
    'partial' : IDL.Null,
  });
  const ExecutionScope = IDL.Variant({
    'full' : IDL.Null,
    'single' : IDL.Null,
    'partial' : IDL.Null,
  });
  const NodeExecutionLog = IDL.Record({
    'nodeId' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'inputs' : IDL.Text,
    'durationMs' : IDL.Nat,
    'outputs' : IDL.Text,
    'nodeType' : IDL.Text,
  });
  const AppendExecutionRequest = IDL.Record({
    'status' : ExecutionStatus,
    'scope' : ExecutionScope,
    'durationMs' : IDL.Nat,
    'nodeLogs' : IDL.Vec(NodeExecutionLog),
    'workflowId' : IDL.Text,
  });
  const Time = IDL.Int;
  const Execution = IDL.Record({
    'id' : IDL.Text,
    'status' : ExecutionStatus,
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'scope' : ExecutionScope,
    'durationMs' : IDL.Nat,
    'nodeLogs' : IDL.Vec(NodeExecutionLog),
    'workflowId' : IDL.Text,
  });
  const WorkflowEdge = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'targetHandle' : IDL.Opt(IDL.Text),
    'target' : IDL.Text,
    'sourceHandle' : IDL.Opt(IDL.Text),
  });
  const NodeData = IDL.Record({ 'config' : IDL.Text, 'nodeType' : IDL.Text });
  const NodePosition = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const WorkflowNode = IDL.Record({
    'id' : IDL.Text,
    'data' : NodeData,
    'position' : NodePosition,
    'nodeType' : IDL.Text,
  });
  const CreateWorkflowRequest = IDL.Record({
    'name' : IDL.Text,
    'edges' : IDL.Vec(WorkflowEdge),
    'nodes' : IDL.Vec(WorkflowNode),
  });
  const Workflow = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'edges' : IDL.Vec(WorkflowEdge),
    'updatedAt' : Time,
    'nodes' : IDL.Vec(WorkflowNode),
  });
  const ExecutionSummary = IDL.Record({
    'id' : IDL.Text,
    'status' : ExecutionStatus,
    'createdAt' : Time,
    'scope' : ExecutionScope,
    'durationMs' : IDL.Nat,
    'workflowId' : IDL.Text,
  });
  const ExecutionDetail = IDL.Record({
    'summary' : ExecutionSummary,
    'nodeLogs' : IDL.Vec(NodeExecutionLog),
  });
  const ExecutionResult = IDL.Variant({
    'ok' : ExecutionDetail,
    'err' : IDL.Text,
  });
  const WorkflowSummary = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'edgeCount' : IDL.Nat,
    'nodeCount' : IDL.Nat,
  });
  const UpdateWorkflowRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'edges' : IDL.Vec(WorkflowEdge),
    'nodes' : IDL.Vec(WorkflowNode),
  });
  const WorkflowResult = IDL.Variant({ 'ok' : Workflow, 'err' : IDL.Text });
  
  return IDL.Service({
    'appendExecution' : IDL.Func([AppendExecutionRequest], [Execution], []),
    'createWorkflow' : IDL.Func([CreateWorkflowRequest], [Workflow], []),
    'deleteWorkflow' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getExecution' : IDL.Func([IDL.Text], [ExecutionResult], ['query']),
    'getWorkflow' : IDL.Func([IDL.Text], [IDL.Opt(Workflow)], ['query']),
    'listExecutions' : IDL.Func([], [IDL.Vec(ExecutionSummary)], ['query']),
    'listWorkflows' : IDL.Func([], [IDL.Vec(WorkflowSummary)], ['query']),
    'updateWorkflow' : IDL.Func([UpdateWorkflowRequest], [WorkflowResult], []),
  });
};

export const init = ({ IDL }) => { return []; };