/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppendExecutionRequest {
  'status' : ExecutionStatus,
  'scope' : ExecutionScope,
  'durationMs' : bigint,
  'nodeLogs' : Array<NodeExecutionLog>,
  'workflowId' : string,
}
export interface CreateWorkflowRequest {
  'name' : string,
  'edges' : Array<WorkflowEdge>,
  'nodes' : Array<WorkflowNode>,
}
export interface Execution {
  'id' : string,
  'status' : ExecutionStatus,
  'ownerId' : Principal,
  'createdAt' : Time,
  'scope' : ExecutionScope,
  'durationMs' : bigint,
  'nodeLogs' : Array<NodeExecutionLog>,
  'workflowId' : string,
}
export interface ExecutionDetail {
  'summary' : ExecutionSummary,
  'nodeLogs' : Array<NodeExecutionLog>,
}
export type ExecutionResult = { 'ok' : ExecutionDetail } |
  { 'err' : string };
export type ExecutionScope = { 'full' : null } |
  { 'single' : null } |
  { 'partial' : null };
export type ExecutionStatus = { 'success' : null } |
  { 'failed' : null } |
  { 'partial' : null };
export interface ExecutionSummary {
  'id' : string,
  'status' : ExecutionStatus,
  'createdAt' : Time,
  'scope' : ExecutionScope,
  'durationMs' : bigint,
  'workflowId' : string,
}
export interface NodeData { 'config' : string, 'nodeType' : string }
export interface NodeExecutionLog {
  'nodeId' : string,
  'error' : [] | [string],
  'inputs' : string,
  'durationMs' : bigint,
  'outputs' : string,
  'nodeType' : string,
}
export interface NodePosition { 'x' : number, 'y' : number }
export type Time = bigint;
export interface UpdateWorkflowRequest {
  'id' : string,
  'name' : string,
  'edges' : Array<WorkflowEdge>,
  'nodes' : Array<WorkflowNode>,
}
export interface Workflow {
  'id' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'edges' : Array<WorkflowEdge>,
  'updatedAt' : Time,
  'nodes' : Array<WorkflowNode>,
}
export interface WorkflowEdge {
  'id' : string,
  'source' : string,
  'targetHandle' : [] | [string],
  'target' : string,
  'sourceHandle' : [] | [string],
}
export interface WorkflowNode {
  'id' : string,
  'data' : NodeData,
  'position' : NodePosition,
  'nodeType' : string,
}
export type WorkflowResult = { 'ok' : Workflow } |
  { 'err' : string };
export interface WorkflowSummary {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'edgeCount' : bigint,
  'nodeCount' : bigint,
}
export interface _SERVICE {
  'appendExecution' : ActorMethod<[AppendExecutionRequest], Execution>,
  'createWorkflow' : ActorMethod<[CreateWorkflowRequest], Workflow>,
  'deleteWorkflow' : ActorMethod<[string], boolean>,
  'getExecution' : ActorMethod<[string], ExecutionResult>,
  'getWorkflow' : ActorMethod<[string], [] | [Workflow]>,
  'listExecutions' : ActorMethod<[], Array<ExecutionSummary>>,
  'listWorkflows' : ActorMethod<[], Array<WorkflowSummary>>,
  'updateWorkflow' : ActorMethod<[UpdateWorkflowRequest], WorkflowResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];