/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NodeExecutionLog {
    nodeId: string;
    error?: string;
    inputs: string;
    durationMs: bigint;
    outputs: string;
    nodeType: string;
}
export interface NodeData {
    config: string;
    nodeType: string;
}
export type Time = bigint;
export type ExecutionResult = {
    __kind__: "ok";
    ok: ExecutionDetail;
} | {
    __kind__: "err";
    err: string;
};
export interface WorkflowNode {
    id: string;
    data: NodeData;
    position: NodePosition;
    nodeType: string;
}
export interface WorkflowEdge {
    id: string;
    source: string;
    targetHandle?: string;
    target: string;
    sourceHandle?: string;
}
export interface NodePosition {
    x: number;
    y: number;
}
export interface ExecutionSummary {
    id: string;
    status: ExecutionStatus;
    createdAt: Time;
    scope: ExecutionScope;
    durationMs: bigint;
    workflowId: string;
}
export interface WorkflowSummary {
    id: string;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    edgeCount: bigint;
    nodeCount: bigint;
}
export interface ExecutionDetail {
    summary: ExecutionSummary;
    nodeLogs: Array<NodeExecutionLog>;
}
export interface Execution {
    id: string;
    status: ExecutionStatus;
    ownerId: Principal;
    createdAt: Time;
    scope: ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<NodeExecutionLog>;
    workflowId: string;
}
export interface AppendExecutionRequest {
    status: ExecutionStatus;
    scope: ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<NodeExecutionLog>;
    workflowId: string;
}
export interface CreateWorkflowRequest {
    name: string;
    edges: Array<WorkflowEdge>;
    nodes: Array<WorkflowNode>;
}
export type WorkflowResult = {
    __kind__: "ok";
    ok: Workflow;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateWorkflowRequest {
    id: string;
    name: string;
    edges: Array<WorkflowEdge>;
    nodes: Array<WorkflowNode>;
}
export interface Workflow {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    edges: Array<WorkflowEdge>;
    updatedAt: Time;
    nodes: Array<WorkflowNode>;
}
export enum ExecutionScope {
    full = "full",
    single = "single",
    partial = "partial"
}
export enum ExecutionStatus {
    success = "success",
    failed = "failed",
    partial = "partial"
}
export interface backendInterface {
    appendExecution(req: AppendExecutionRequest): Promise<Execution>;
    createWorkflow(req: CreateWorkflowRequest): Promise<Workflow>;
    deleteWorkflow(id: string): Promise<boolean>;
    getExecution(executionId: string): Promise<ExecutionResult>;
    getWorkflow(id: string): Promise<Workflow | null>;
    listExecutions(): Promise<Array<ExecutionSummary>>;
    listWorkflows(): Promise<Array<WorkflowSummary>>;
    updateWorkflow(req: UpdateWorkflowRequest): Promise<WorkflowResult>;
}
import type { AppendExecutionRequest as _AppendExecutionRequest, CreateWorkflowRequest as _CreateWorkflowRequest, Execution as _Execution, ExecutionDetail as _ExecutionDetail, ExecutionResult as _ExecutionResult, ExecutionScope as _ExecutionScope, ExecutionStatus as _ExecutionStatus, ExecutionSummary as _ExecutionSummary, NodeExecutionLog as _NodeExecutionLog, Time as _Time, UpdateWorkflowRequest as _UpdateWorkflowRequest, Workflow as _Workflow, WorkflowEdge as _WorkflowEdge, WorkflowNode as _WorkflowNode, WorkflowResult as _WorkflowResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async appendExecution(arg0: AppendExecutionRequest): Promise<Execution> {
        if (this.processError) {
            try {
                const result = await this.actor.appendExecution(to_candid_AppendExecutionRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Execution_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendExecution(to_candid_AppendExecutionRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Execution_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWorkflow(arg0: CreateWorkflowRequest): Promise<Workflow> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkflow(to_candid_CreateWorkflowRequest_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Workflow_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkflow(to_candid_CreateWorkflowRequest_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Workflow_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWorkflow(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkflow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkflow(arg0);
            return result;
        }
    }
    async getExecution(arg0: string): Promise<ExecutionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getExecution(arg0);
                return from_candid_ExecutionResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExecution(arg0);
            return from_candid_ExecutionResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkflow(arg0: string): Promise<Workflow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflow(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflow(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExecutions(): Promise<Array<ExecutionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExecutions();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExecutions();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWorkflows(): Promise<Array<WorkflowSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkflows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkflows();
            return result;
        }
    }
    async updateWorkflow(arg0: UpdateWorkflowRequest): Promise<WorkflowResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkflow(to_candid_UpdateWorkflowRequest_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkflowResult_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkflow(to_candid_UpdateWorkflowRequest_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkflowResult_n40(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExecutionDetail_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionDetail): ExecutionDetail {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionResult): ExecutionResult {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionScope_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionScope): ExecutionScope {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionStatus): ExecutionStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ExecutionSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExecutionSummary): ExecutionSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Execution_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Execution): Execution {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_NodeExecutionLog_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NodeExecutionLog): NodeExecutionLog {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WorkflowEdge_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowEdge): WorkflowEdge {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WorkflowResult_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowResult): WorkflowResult {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Workflow_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Workflow): Workflow {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Workflow]): Workflow | null {
    return value.length === 0 ? null : from_candid_Workflow_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ExecutionStatus;
    ownerId: Principal;
    createdAt: _Time;
    scope: _ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<_NodeExecutionLog>;
    workflowId: string;
}): {
    id: string;
    status: ExecutionStatus;
    ownerId: Principal;
    createdAt: Time;
    scope: ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<NodeExecutionLog>;
    workflowId: string;
} {
    return {
        id: value.id,
        status: from_candid_ExecutionStatus_n12(_uploadFile, _downloadFile, value.status),
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        scope: from_candid_ExecutionScope_n14(_uploadFile, _downloadFile, value.scope),
        durationMs: value.durationMs,
        nodeLogs: from_candid_vec_n16(_uploadFile, _downloadFile, value.nodeLogs),
        workflowId: value.workflowId
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nodeId: string;
    error: [] | [string];
    inputs: string;
    durationMs: bigint;
    outputs: string;
    nodeType: string;
}): {
    nodeId: string;
    error?: string;
    inputs: string;
    durationMs: bigint;
    outputs: string;
    nodeType: string;
} {
    return {
        nodeId: value.nodeId,
        error: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.error)),
        inputs: value.inputs,
        durationMs: value.durationMs,
        outputs: value.outputs,
        nodeType: value.nodeType
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: _Time;
    edges: Array<_WorkflowEdge>;
    updatedAt: _Time;
    nodes: Array<_WorkflowNode>;
}): {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    edges: Array<WorkflowEdge>;
    updatedAt: Time;
    nodes: Array<WorkflowNode>;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        edges: from_candid_vec_n27(_uploadFile, _downloadFile, value.edges),
        updatedAt: value.updatedAt,
        nodes: value.nodes
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    source: string;
    targetHandle: [] | [string];
    target: string;
    sourceHandle: [] | [string];
}): {
    id: string;
    source: string;
    targetHandle?: string;
    target: string;
    sourceHandle?: string;
} {
    return {
        id: value.id,
        source: value.source,
        targetHandle: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.targetHandle)),
        target: value.target,
        sourceHandle: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.sourceHandle))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    summary: _ExecutionSummary;
    nodeLogs: Array<_NodeExecutionLog>;
}): {
    summary: ExecutionSummary;
    nodeLogs: Array<NodeExecutionLog>;
} {
    return {
        summary: from_candid_ExecutionSummary_n34(_uploadFile, _downloadFile, value.summary),
        nodeLogs: from_candid_vec_n16(_uploadFile, _downloadFile, value.nodeLogs)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ExecutionStatus;
    createdAt: _Time;
    scope: _ExecutionScope;
    durationMs: bigint;
    workflowId: string;
}): {
    id: string;
    status: ExecutionStatus;
    createdAt: Time;
    scope: ExecutionScope;
    durationMs: bigint;
    workflowId: string;
} {
    return {
        id: value.id,
        status: from_candid_ExecutionStatus_n12(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        scope: from_candid_ExecutionScope_n14(_uploadFile, _downloadFile, value.scope),
        durationMs: value.durationMs,
        workflowId: value.workflowId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    failed: null;
} | {
    partial: null;
}): ExecutionStatus {
    return "success" in value ? ExecutionStatus.success : "failed" in value ? ExecutionStatus.failed : "partial" in value ? ExecutionStatus.partial : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    full: null;
} | {
    single: null;
} | {
    partial: null;
}): ExecutionScope {
    return "full" in value ? ExecutionScope.full : "single" in value ? ExecutionScope.single : "partial" in value ? ExecutionScope.partial : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ExecutionDetail;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ExecutionDetail;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ExecutionDetail_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Workflow;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Workflow;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Workflow_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NodeExecutionLog>): Array<NodeExecutionLog> {
    return value.map((x)=>from_candid_NodeExecutionLog_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkflowEdge>): Array<WorkflowEdge> {
    return value.map((x)=>from_candid_WorkflowEdge_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExecutionSummary>): Array<ExecutionSummary> {
    return value.map((x)=>from_candid_ExecutionSummary_n34(_uploadFile, _downloadFile, x));
}
function to_candid_AppendExecutionRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppendExecutionRequest): _AppendExecutionRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateWorkflowRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateWorkflowRequest): _CreateWorkflowRequest {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ExecutionScope_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExecutionScope): _ExecutionScope {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ExecutionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExecutionStatus): _ExecutionStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NodeExecutionLog_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NodeExecutionLog): _NodeExecutionLog {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateWorkflowRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateWorkflowRequest): _UpdateWorkflowRequest {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_WorkflowEdge_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowEdge): _WorkflowEdge {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ExecutionStatus;
    scope: ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<NodeExecutionLog>;
    workflowId: string;
}): {
    status: _ExecutionStatus;
    scope: _ExecutionScope;
    durationMs: bigint;
    nodeLogs: Array<_NodeExecutionLog>;
    workflowId: string;
} {
    return {
        status: to_candid_ExecutionStatus_n3(_uploadFile, _downloadFile, value.status),
        scope: to_candid_ExecutionScope_n5(_uploadFile, _downloadFile, value.scope),
        durationMs: value.durationMs,
        nodeLogs: to_candid_vec_n7(_uploadFile, _downloadFile, value.nodeLogs),
        workflowId: value.workflowId
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    edges: Array<WorkflowEdge>;
    nodes: Array<WorkflowNode>;
}): {
    name: string;
    edges: Array<_WorkflowEdge>;
    nodes: Array<_WorkflowNode>;
} {
    return {
        name: value.name,
        edges: to_candid_vec_n22(_uploadFile, _downloadFile, value.edges),
        nodes: value.nodes
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    source: string;
    targetHandle?: string;
    target: string;
    sourceHandle?: string;
}): {
    id: string;
    source: string;
    targetHandle: [] | [string];
    target: string;
    sourceHandle: [] | [string];
} {
    return {
        id: value.id,
        source: value.source,
        targetHandle: value.targetHandle ? candid_some(value.targetHandle) : candid_none(),
        target: value.target,
        sourceHandle: value.sourceHandle ? candid_some(value.sourceHandle) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    edges: Array<WorkflowEdge>;
    nodes: Array<WorkflowNode>;
}): {
    id: string;
    name: string;
    edges: Array<_WorkflowEdge>;
    nodes: Array<_WorkflowNode>;
} {
    return {
        id: value.id,
        name: value.name,
        edges: to_candid_vec_n22(_uploadFile, _downloadFile, value.edges),
        nodes: value.nodes
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nodeId: string;
    error?: string;
    inputs: string;
    durationMs: bigint;
    outputs: string;
    nodeType: string;
}): {
    nodeId: string;
    error: [] | [string];
    inputs: string;
    durationMs: bigint;
    outputs: string;
    nodeType: string;
} {
    return {
        nodeId: value.nodeId,
        error: value.error ? candid_some(value.error) : candid_none(),
        inputs: value.inputs,
        durationMs: value.durationMs,
        outputs: value.outputs,
        nodeType: value.nodeType
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExecutionStatus): {
    success: null;
} | {
    failed: null;
} | {
    partial: null;
} {
    return value == ExecutionStatus.success ? {
        success: null
    } : value == ExecutionStatus.failed ? {
        failed: null
    } : value == ExecutionStatus.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExecutionScope): {
    full: null;
} | {
    single: null;
} | {
    partial: null;
} {
    return value == ExecutionScope.full ? {
        full: null
    } : value == ExecutionScope.single ? {
        single: null
    } : value == ExecutionScope.partial ? {
        partial: null
    } : value;
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkflowEdge>): Array<_WorkflowEdge> {
    return value.map((x)=>to_candid_WorkflowEdge_n23(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<NodeExecutionLog>): Array<_NodeExecutionLog> {
    return value.map((x)=>to_candid_NodeExecutionLog_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
